# Generated by Django 4.2.11 on 2024-05-31 13:54

from django.db import migrations
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_post_options_post_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='created_date',
            field=django_jalali.db.models.jDateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='published_date',
            field=django_jalali.db.models.jDateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='updated_date',
            field=django_jalali.db.models.jDateTimeField(auto_now=True),
        ),
    ]
